// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM6K-P-Zw2RTqM00sJiYOUoNl6bsshsqU',
    appId: '1:917839498875:web:baaca16a02e3fb1376dcde',
    messagingSenderId: '917839498875',
    projectId: 'kigali-city-services-812e0',
    authDomain: 'kigali-city-services-812e0.firebaseapp.com',
    storageBucket: 'kigali-city-services-812e0.firebasestorage.app',
    measurementId: 'G-ZVW5Y3P3PJ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCEplaKmbiTz2-8Zah2WOJRYMb5fYzGWg',
    appId: '1:917839498875:ios:a7caacd0f800b6a976dcde',
    messagingSenderId: '917839498875',
    projectId: 'kigali-city-services-812e0',
    storageBucket: 'kigali-city-services-812e0.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityDirectory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCEplaKmbiTz2-8Zah2WOJRYMb5fYzGWg',
    appId: '1:917839498875:ios:a7caacd0f800b6a976dcde',
    messagingSenderId: '917839498875',
    projectId: 'kigali-city-services-812e0',
    storageBucket: 'kigali-city-services-812e0.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityDirectory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM6K-P-Zw2RTqM00sJiYOUoNl6bsshsqU',
    appId: '1:917839498875:web:d1403ac6077d175a76dcde',
    messagingSenderId: '917839498875',
    projectId: 'kigali-city-services-812e0',
    authDomain: 'kigali-city-services-812e0.firebaseapp.com',
    storageBucket: 'kigali-city-services-812e0.firebasestorage.app',
    measurementId: 'G-0579LPVZXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYdyv-5Bh740HgEMMXVBTxt7D6zc2ZCNM',
    appId: '1:917839498875:android:930bc4e2fb8554e276dcde',
    messagingSenderId: '917839498875',
    projectId: 'kigali-city-services-812e0',
    storageBucket: 'kigali-city-services-812e0.firebasestorage.app',
  );

}